### ISSUE TITLE
F-Droid Release

### ISSUE THREAD

**Issue by ZdenkoRufati** [Delta-Icons/android#47]
What do you think of having Delta Icons on [F-Droid](https://f-droid.org/en/)?

> F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform. The client makes it easy to browse, install, and keep track of updates on your device.

FYI, @Poussinou, @IzzySoft & @Rudloff

**Comment by leifniem** [comment]
I would be fine with that since Delta is open source and licensed for non-commerical use.
I think the greatest hiccup we'd face would be the license check currently in place relying on Google Play Services. Though that has proven to be no hurdle towards people trying to make money off of Delta so far i guess.

**Comment by IzzySoft** [comment]
Thanks @leifniem – but …

@ZdenkoRufati Afraid CC-BY-NC-ND (the license used here according to the readme) is not accepted by F-Droid. Must be [one of these](https://spdx.org/licenses/) and floss-compatible.

**Comment by leifniem** [comment]
I need to take a look at the no derivatives part then, maybe I jumped the
boat on that part without thinking.

Izzy <notifications@github.com> schrieb am Mo., 8. Apr. 2019, 00:43:

**Comment by IzzySoft** [comment]
@leifniem yeah, that's the hardest restriction in terms of FLOSS. But the NC will also be rejected AFAIK. CC-BY, CC-BY-SA-4.0 and CC0 (PublicDomain) are the only CCs one from the list that should fit (with a check-mark in the FLOSS column) – but I don't know if you'd go for one of those.

**Comment by leifniem** [comment]
Sorry for only getting back to this issue now. I took the time to look at the licenses and the issue i run into is that they all allow using the icons commercially. That's kinda of a hiccup because i'm pretty sure people would fail to release the products using them under the same license, even if required.

**Comment by IzzySoft** [comment]
But you'd expect them to respect the NC part? If they don't respect the license, that makes no difference IMHO.

**Comment by leifniem** [comment]
Fair point. My example to think about was a case where someone asked to use the icons in an indie movie, which probably can't be released under open source licenses in most cases. 

On the other hand the only encounters I had with people using the icons were ripoffs or test ports for personal use with proper attribution. So it's a 50/50 on the respecting part.

**Comment by IzzySoft** [comment]
It always is. Ya know, there are 10 different kind of people: those who understand binary, and those who don't… :wink:
